[toolchain]
anchor_version = "0.31.1"

[features]
resolution = false
skip-lint = false

[programs.localnet]
oft = "Cd9auhxkC8HpyykvDWeJonMn5q15aggaYdnBtnBaBgaV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./junk-id.json"

[scripts]
test = "npx jest test/anchor"
